apiVersion: v1
kind: Service
metadata:
  name: myproject-service
  namespace: myproject
spec:
  selector:
    app: myproject
  ports:
    - name: http
      port: 8090
      targetPort: http
  type: NodePort

